import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        id="tailwindjitcdn"
        src="https://unpkg.com/tailwindcss-jit-cdn"
        // onLoad={() => {
        // }}
      />

      <main className={styles.main}>
        <h1 className={styles.title}>
          {/* Aswani weds Vishnu */}
          To Infinity and Beyond! Yo
        </h1>

      </main>

      <footer className={styles.footer}>
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="https://firebasestorage.googleapis.com/v0/b/portfolio-bb9f1.appspot.com/o/images%2Fprrelax.png?alt=media&token=5e05bc37-9ebe-4c27-ab38-163a09472160"
            alt="Techrush Logo" 
            width={72} height={72} />
          </span>
      </footer>
    </div>
  )
}

export default Home
